// <auto-generated />
namespace NLayer.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addHeadingStatusAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addHeadingStatusAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202105260923584_addHeadingStatusAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
